---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abrahamsc-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: abrahamsc-mysql-deployment
spec:
  selector:
    matchLabels:
      app: abrahamsc-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: abrahamsc-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: abrahamsc-mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: abrahamsc-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: test
        ports:
        - containerPort: 3306
          name: abrahamsc-mysql
        volumeMounts:
        - name: abrahamsc-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: abrahamsc-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: abrahamsc-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: abrahamsc-mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: abrahamsc-mysql